### ISSUE TITLE
The app icon is not shown in AppCenter correctly

### ISSUE THREAD

**Issue by ryonakano** [lainsce/rakugaki#4]
![Screenshot from 2020-01-22 22-21-39](https://user-images.githubusercontent.com/26003928/72897622-b374f800-3d65-11ea-921e-6c266723abb7.png)

The app icon that seems to contain the Japanese character 落書き does not seem to be rendered correctly in AppCenter.

**Comment by lainsce** [comment]
Will fix soon.
